# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Connecting the dots
tagline:             "musings and meanderings"
description:         'Random thoughts, wierd insights and wonkish rants.'
url:                 http://auag92.github.io
baseurl:             /blog
paginate:            10

# About/contact
author:
  name:              Apaar Shanker
  url:               https://twitter.com/ShankerApaar
  email:             apaar92@gmail.com

# Custom vars
version:             1.0.0

gems: ["emoji_for_jekyll"]

timezone: Asia/Kolkata
future: False
