# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Chocolate Fudge
tagline:             'My Blog'
description:         'This blog shall purvey random meanderings of the mind of the great Mr. Apaar Shanker'
url:                 http://auag92.github.io
baseurl:             /blog
paginate:            10

# About/contact
author:
  name:              Apaar Shanker
  url:               https://twitter.com/apaarshanker
  email:             apaar92@gmail.com

# Custom vars
version:             1.0.0
